// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfoM36RPA1h5nc479GvEzK6e5innJc7g',
    appId: '1:827605236275:web:950688f0339a4448914146',
    messagingSenderId: '827605236275',
    projectId: 'mindful-state-auth',
    authDomain: 'mindful-state-auth.firebaseapp.com',
    storageBucket: 'mindful-state-auth.appspot.com',
    measurementId: 'G-3LPX2HTCGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bTr4DBBNOtM9UTKR8AWaCiGuy7fR9is',
    appId: '1:827605236275:android:19bf16668a455d0e914146',
    messagingSenderId: '827605236275',
    projectId: 'mindful-state-auth',
    storageBucket: 'mindful-state-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs4VL_YDXoOwaVkQUXIOHSF0gqevq8c3M',
    appId: '1:827605236275:ios:c5ce3c57bff4694e914146',
    messagingSenderId: '827605236275',
    projectId: 'mindful-state-auth',
    storageBucket: 'mindful-state-auth.appspot.com',
    androidClientId: '827605236275-1ka1c3caqerbd4p83t3k884i4icis4s5.apps.googleusercontent.com',
    iosClientId: '827605236275-9f692o1gvgtjgsuhfofkdd8vrtg6jpr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindfulState',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs4VL_YDXoOwaVkQUXIOHSF0gqevq8c3M',
    appId: '1:827605236275:ios:c5ce3c57bff4694e914146',
    messagingSenderId: '827605236275',
    projectId: 'mindful-state-auth',
    storageBucket: 'mindful-state-auth.appspot.com',
    androidClientId: '827605236275-1ka1c3caqerbd4p83t3k884i4icis4s5.apps.googleusercontent.com',
    iosClientId: '827605236275-9f692o1gvgtjgsuhfofkdd8vrtg6jpr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindfulState',
  );
}
